# -*- coding: utf-8 -*-
"""construction_permits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MVdGb7Ak3MxZHpoRl2WLVErCNluA_CvY

# Construction Permits – Uster

**Pipeline:**
1. Fetch raw permit publications from amtsblattportal.ch
2. Parse addresses from titles (handles multiple addresses per permit)
3. Explode to one row per address (same `id`)
4. Geocode: swisstopo API (primary) → Nominatim (fallback)
5. Spatial join with plots to assign plot polygon geometry
6. Export `construction_permits.geojson`

**Geocoding strategy documentation** is in the dedicated section below.

## 0. Dependencies
"""

# ── Feature flags ─────────────────────────────────────────────────────────────
# Set USE_ELASTICSEARCH=True to use ES fuzzy search as an additional geocoding
# fallback. Requires Elasticsearch running on localhost:9200 and:
#   pip install "elasticsearch>=8,<9"
#   docker run -d -p 9200:9200 -e "discovery.type=single-node" \
#     -e "xpack.security.enabled=false" elasticsearch:8.13.0
USE_ELASTICSEARCH = True   # ← change to False to disable

import re
import time
import requests
from io import BytesIO

import polars as pl

import pandas as pd
from shapely.geometry import Point
from tqdm import tqdm
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderQuotaExceeded

"""PLOTS OF LAND (NACHHER EINFÜGEN)"""

import geopandas as gpd
import fiona

test = gpd.read_file("/Users/nathalieguibert/Downloads/PopetyTest/79cb1aec092f4642bcc0cdcdbeb499c2/AV_MOpublic-_Liegenschaften_-OGD/AV_MOpublic-_Liegenschaften_-OGD.gpkg")


test.explore()

# Alle Layer im GeoPackage anzeigen
layers = fiona.listlayers("/Users/nathalieguibert/Downloads/PopetyTest/79cb1aec092f4642bcc0cdcdbeb499c2/AV_MOpublic-_Liegenschaften_-OGD/AV_MOpublic-_Liegenschaften_-OGD.gpkg")
print(layers)

USTER = "bfsnr=198"
liegenschaften_f = gpd.read_file("/Users/nathalieguibert/Downloads/PopetyTest/79cb1aec092f4642bcc0cdcdbeb499c2/AV_MOpublic-_Liegenschaften_-OGD/AV_MOpublic-_Liegenschaften_-OGD.gpkg", layer="avzh_liegenschaften_f", where=USTER)

liegenschaften_f.plot(figsize=(8, 8))
liegenschaften_f.explore()

print(liegenschaften_f.columns)
# Flaechenmass = rounded area, st_area(shape) = exact area
print(liegenschaften_f[["flaechenmass", "st_area(shape)"]][:500])

# Coordinates in Swiss system LV95
liegenschaften_f.to_file("plots_lv95.geojson", driver='GeoJSON')

# Coordinates in worldwide system
liegenschaften_f.to_crs(epsg=4326).to_file("plots_wgs84.geojson", driver="GeoJSON")

"""## 1. Fetch raw permits from amtsblattportal.ch"""

url = "https://amtsblattportal.ch/api/v1/publications/xml"
params = {
    "publicationStates": "PUBLISHED",
    "subRubrics": "BP-ZH01",
    "municipalityId": "198",
    "pageRequest.page": 0,
    "pageRequest.size": 200,
}
r = requests.get(url, params=params)
print(f"Status: {r.status_code}  |  Size: {len(r.text)} chars")
raw_xml = r.text

# Coordinates in Swiss system LV95
liegenschaften_f.to_file("plots_lv95.geojson", driver='GeoJSON')

# Coordinates in worldwide system
liegenschaften_f.to_crs(epsg=4326).to_file("plots_wgs84.geojson", driver="GeoJSON")

"""## 2. Parse XML → Polars DataFrame"""

import lxml.etree as LET

def parse_permits_xml(xml_string: str) -> pl.DataFrame:
    data = []
    context = LET.iterparse(
        BytesIO(xml_string.encode("utf-8")),
        events=("end",),
        tag="{*}publication",
    )
    for _, elem in context:
        meta = elem.find(".//{*}meta")
        reg = meta.find(".//{*}registrationOffice") if meta is not None else None
        data.append({
            "id":          meta.findtext("{*}id")                        if meta else None,
            "pub_date":    meta.findtext("{*}publicationDate")            if meta else None,
            "title":       meta.findtext("{*}title/{*}de")                if meta else None,
            "office_name": reg.findtext("{*}displayName")                 if reg  else None,

        })
        elem.clear()
        while elem.getprevious() is not None:
            del elem.getparent()[0]

    df = pl.DataFrame(data).with_columns(
        pl.col("pub_date").str.to_date("%Y-%m-%d")
    )
    return df

permits_raw = parse_permits_xml(raw_xml)
print(f"Fetched {permits_raw.shape[0]} permits")
permits_raw.head(5)

"""## 3. Address parsing

### Rules
- Strip leading `"bei "` (means *near*, still a valid address if a number follows)
- Remove everything from `Assek.` onwards (building-registry annotations)
- Split on `/` **only** when the right-hand side starts with a street-name word → two separate streets
- Split on `,` **only** when the next token looks like a new street name → two separate streets
- Drop parts with **no digit** (e.g. `"Hinterbreiti Kieswerk"`, `"Chänzeli Sulzbach"`) – cannot geocode without a house number
"""

# Street-type suffixes found in Swiss German addresses
_STREET_RE = re.compile(
    r"(strasse|str\.?|weg|gasse|platz|allee|rain|steig|stieg|halde"
    r"|holz|riet|berg|bühl|bach|wies(?:en)?|roos|matt(?:en)?"
    r"|feld|graben|ring|bogen|park|gässli|ufer|dorf)",
    re.IGNORECASE,
)

def _looks_like_street(s: str) -> bool:
    return bool(_STREET_RE.search(s))


def _expand_number_range(street: str, raw_range: str) -> list[str]:
    """Expand a house-number range into individual addresses.

    Examples:
      "Guldenenstrasse", "14-18"  → ["Guldenenstrasse 14", "Guldenenstrasse 16", "Guldenenstrasse 18"]
      "Burgstrasse",     "34-40"  → ["Burgstrasse 34", "Burgstrasse 36", "Burgstrasse 38", "Burgstrasse 40"]
      "Krämerackerstrasse", "11/11a-11d" → ["Krämerackerstrasse 11", "Krämerackerstrasse 11a", ..., "Krämerackerstrasse 11d"]
    """
    results = []

    # Case: "11/11a-11d" → base number + letter range
    m_letter_range = re.match(r'^(\d+)\s*/\s*\d+([a-z])-\d+([a-z])$', raw_range, re.IGNORECASE)
    if m_letter_range:
        base = int(m_letter_range.group(1))
        l_start = m_letter_range.group(2).lower()
        l_end = m_letter_range.group(3).lower()
        results.append(f"{street} {base}")
        for c in range(ord(l_start), ord(l_end) + 1):
            results.append(f"{street} {base}{chr(c)}")
        return results

    # Case: "14-18" or "34-40" → numeric range, step by 2 (even/odd streets)
    m_num_range = re.match(r'^(\d+)-(\d+)$', raw_range)
    if m_num_range:
        start, end = int(m_num_range.group(1)), int(m_num_range.group(2))
        step = 2 if (end - start) % 2 == 0 and end > start + 1 else 1
        for n in range(start, end + 1, step):
            results.append(f"{street} {n}")
        return results

    # Fallback: return as-is
    return [f"{street} {raw_range}"]


def _expand_same_street_numbers(street: str, numbers: list[str]) -> list[str]:
    """Given a street name and a list of number tokens, return individual addresses.

    Example: "Ackerstrasse", ["28", "32"] → ["Ackerstrasse 28", "Ackerstrasse 32"]
    """
    return [f"{street} {n}" for n in numbers if n.strip()]


def parse_addresses(title: str) -> list[str]:
    """Return a list of full addresses extracted from a permit title.
    Returns [] when no geocodable address can be extracted.
    """
    if not title:
        return []

    # ── extract the free-text part after "Bauprojekt:"
    m = re.search(r"Bauprojekt:\s*(.+)", title)
    print(m)
    if not m:
        return []
    raw = m.group(1)
    print("Bauprojekt separation", raw)

    # ── drop everything from "Assek" (house-registry annotation)
    raw = re.split(r",?\s*[Aa]ssek\.?", raw)[0].strip()
    print("Assek separation", raw)

    # ── strip leading "bei " (means "near", address is still usable)
    raw = re.sub(r"^bei\s+", "", raw, flags=re.IGNORECASE)
    # ── replace inline "bei Nr. X" → "X"  (e.g. "Im Lot bei Nr. 8" → "Im Lot 8")
    raw = re.sub(r"\s+bei\s+Nr\.?\s*", " ", raw, flags=re.IGNORECASE)
    # ── replace " und " between numbers → "/" for uniform splitting
    raw = re.sub(r"\s+und\s+(?=\d)", "/", raw, flags=re.IGNORECASE)
    print("Bei/und separation", raw)

    # ── Step 1: split on " / " (spaced slash) or plain "/"
    slash_parts = re.split(r"\s*/\s*", raw)
    print(slash_parts)

    merged: list[str] = []
    current = slash_parts[0]
    print(current)
    for part in slash_parts[1:]:
        print(part)
        if _looks_like_street(part):
            # Check if part looks like "26, Asylstrasse 25" (digit prefix before a new street)
            digit_prefix = re.match(r'^(\d[\w]*)\s*,\s*(.+)', part)
            if digit_prefix:
                current = current + "/" + digit_prefix.group(1)
                print(current.strip())
                merged.append(current.strip())
                current = digit_prefix.group(2).strip()
            else:
                print(current.strip())
                merged.append(current.strip())
                current = part.strip()
        else:
            current = current + "/" + part
            print(current)
            print("end")
    merged.append(current.strip())

    # ── Step 2: for each part, split on ", " where next token is a new street
    street_parts: list[str] = []
    for part in merged:
        sub = re.split(r",\s*", part)
        cur = sub[0]
        for s in sub[1:]:
            if _looks_like_street(s):
                street_parts.append(cur.strip())
                cur = s.strip()
        street_parts.append(cur.strip())

    # ── Step 3: expand ranges and same-street multi-numbers, then filter
    valid: list[str] = []
    for addr in street_parts:
        addr = addr.strip()
        if not addr:
            continue

        # Extract street name and the number part
        # e.g. "Guldenenstrasse 14-18" → street="Guldenenstrasse", nums="14-18"
        m_street = re.match(r'^(.+?)\s+(\d[\w/\-]*)$', addr)
        if m_street:
            street_name = m_street.group(1).strip()
            num_part    = m_street.group(2).strip()

            # numeric range: "14-18", "34-40"
            if re.match(r'^\d+-\d+$', num_part):
                expanded = _expand_number_range(street_name, num_part)
                valid.extend(f"{a}, Uster, 8610, Switzerland" for a in expanded)
                continue

            # letter range with base: "11/11a-11d"
            if re.match(r'^\d+/\d+[a-z]-\d+[a-z]$', num_part, re.IGNORECASE):
                expanded = _expand_number_range(street_name, num_part)
                valid.extend(f"{a}, Uster, 8610, Switzerland" for a in expanded)
                continue

            # same-street slash numbers: "28/32", "2/4", "25/27", "24/26"
            # only if all slash parts are purely numeric (no street words)
            slash_nums = num_part.split("/")
            if len(slash_nums) > 1 and all(re.match(r'^\d+[a-z]?$', p, re.IGNORECASE) for p in slash_nums):
                expanded = _expand_same_street_numbers(street_name, slash_nums)
                valid.extend(f"{a}, Uster, 8610, Switzerland" for a in expanded)
                continue

        # default: keep as-is if has digit or street suffix
        if re.search(r"\d", addr) or _looks_like_street(addr):
            valid.append(f"{addr}, Uster, 8610, Switzerland")

    return valid


# ── Quick sanity-check on the tricky cases
test_cases = [
    ("Bauprojekt: Chammerholzstr. 10/Fehraltorferstrasse 18a/18b, Assek. Nrn. 5709/5573, Uster",
     ["Chammerholzstr. 10, Uster, 8610, Switzerland",
      "Fehraltorferstrasse 18a/18b, Uster, 8610, Switzerland"]),
    ("Bauprojekt: Sandstrasse 2, Seestrasse 26/28, Assek. Nr. 2591, 2578, Uster",
     ["Sandstrasse 2, Uster, 8610, Switzerland",
      "Seestrasse 26/28, Uster, 8610, Switzerland"]),
    ("Bauprojekt: Winterthurerstrasse 49/49a, Assek. Nr. 880/676, Uster",
     ["Winterthurerstrasse 49/49a, Uster, 8610, Switzerland"]),
    ("Bauprojekt: bei Schwerzistrasse 60, Uster",
     ["Schwerzistrasse 60, Uster, 8610, Switzerland"]),
    ("Bauprojekt: Hinterbreiti Kieswerk, Uster",
     []),  # no digit → skipped
    ("Bauprojekt: Alpenblickstrasse 24/26, Asylstrasse 25/27, Wagerenstrasse 21/23, Uster",
     ["Alpenblickstrasse 24/26, Uster, 8610, Switzerland",
      "Asylstrasse 25/27, Uster, 8610, Switzerland",
      "Wagerenstrasse 21/23, Uster, 8610, Switzerland"]),
]

all_ok = True
debug_rows = []

for title, expected in test_cases:
    got = parse_addresses(title)
    ok = got == expected
    if not ok:
        all_ok = False
        # capture each intermediate split step for inspection
        m2 = re.search(r"Bauprojekt:\s*(.+)", title)
        raw0        = m2.group(1) if m2 else ""
        after_assek = re.split(r",?\s*[Aa]ssek\.?", raw0)[0].strip()
        after_bei   = re.sub(r"^bei\s+", "", after_assek, flags=re.IGNORECASE)
        slash_parts = re.split(r"\s*/\s*", after_bei)
        _merged: list[str] = []
        _cur = slash_parts[0]
        for p in slash_parts[1:]:
            if _looks_like_street(p):
                _merged.append(_cur.strip())
                _cur = p.strip()
            else:
                _cur = _cur + "/" + p
        _merged.append(_cur.strip())
        _street_parts: list[str] = []
        for part in _merged:
            sub = re.split(r",\s*", part)
            c = sub[0]
            for s in sub[1:]:
                if _looks_like_street(s):
                    _street_parts.append(c.strip())
                    c = s.strip()
            _street_parts.append(c.strip())
        debug_rows.append({
            "title":        title,
            "after_assek":  after_assek,
            "after_bei":    after_bei,
            "slash_parts":  str(slash_parts),
            "merged_parts": str(_merged),
            "street_parts": str(_street_parts),
            "got":          str(got),
            "expected":     str(expected),
        })

    status = "✓" if ok else "✗"
    print(f"{status}  {title[:60]}")
    if not ok:
        print(f"   expected: {expected}")
        print(f"   got:      {got}")

print("\nAll tests passed!" if all_ok else "\nSome tests FAILED – review parse_addresses()")

# DataFrame with one row per failed test case, showing every intermediate step
parse_debug_df = pd.DataFrame(debug_rows)
if not parse_debug_df.empty:
    print(f"\n{len(parse_debug_df)} failed case(s) captured in parse_debug_df")
    print(parse_debug_df)
    print("END")

"""## 4. Explode: one row per address"""

# Build exploded pandas DataFrame (polars explode needs list column)
rows = []

for row in permits_raw.iter_rows(named=True):
    addresses = parse_addresses(row["title"])
    if not addresses:
        rows.append({**row, "project_address": None, "parse_status": "no_address"})
    else:
        for addr in addresses:
            # street_only = has a street suffix but no digit (e.g. "Aathalstrasse")
            status = "street_only" if not re.search(r"\d", addr) else "ok"
            rows.append({**row, "project_address": addr, "parse_status": status})

permits_exploded = pd.DataFrame(rows)

multi = len(permits_exploded) - len(permits_raw)
print(f"Original permits  : {len(permits_raw)}")
print(f"Rows after explode: {len(permits_exploded)}  (+{multi} from multi-address permits)")
print(permits_exploded["parse_status"].value_counts())
print("\nAddresses flagged as no_address (geocoding will be skipped):")
no_addr = permits_exploded[permits_exploded["parse_status"] == "no_address"][["id", "title"]]
for _, r in no_addr.iterrows():
    print(f"  {r['title']}")
print("\nAddresses flagged as street_only (geocoding will be attempted, may return street midpoint):")
street_only = permits_exploded[permits_exploded["parse_status"] == "street_only"][["id", "title", "project_address"]]
for _, r in street_only.iterrows():
    print(f"  {r['project_address']}  ←  {r['title'][:70]}")

permits_exploded[["id", "title", "project_address", "parse_status"]]

"""## 5. Geocoding

### Strategy

| Step | Tool | Why |
|------|------|-----|
| Primary | **swisstopo geocoding API** (`api3.geo.admin.ch`) | Swiss federal address register, covers every official Swiss address including local variants |
| Fallback | **Nominatim** (OpenStreetMap) | Global coverage, good for named buildings; slower, rate-limited to 1 req/s |
| Skip | Addresses with **no digit** | Floor names / field names (e.g. "Hinterbreiti Kieswerk") cannot be resolved to a precise point |

Validation: results are checked against the Uster municipality boundary (from `plots_wgs84.geojson`).
"""

# Load plots for boundary validation and spatial join
# Adjust path if your plots file is elsewhere
PLOTS_PATH = "plots_wgs84.geojson"
plots = gpd.read_file(PLOTS_PATH)
plots = plots.to_crs(epsg=4326) #wgs84

uster_boundary = plots.dissolve().geometry.iloc[0]
print(uster_boundary)
print(f"Plots loaded: {len(plots)} parcels, CRS: {plots.crs}")

nominatim = Nominatim(user_agent="popety_permits_pipeline")
_geocode_cache: dict[str, tuple[float, float] | None] = {}


def _in_uster(lat: float, lon: float) -> bool:
    return uster_boundary.contains(Point(lon, lat))


def geocode_swisstopo(addr: str) -> tuple[float, float] | None:
    """Query the swisstopo location search API. Returns (lat, lon) or None.

    Validation: the street name from the query must appear in swisstopo's
    returned 'detail' field. This catches cases where swisstopo returns a
    plausible-looking point that is actually a different street.
    """
    params = {
        "type": "locations",
        "searchText": addr,
        "lang": "de",
        "limit": 1,
        "sr": "4326",
    }
    try:
        resp = requests.get(
            "https://api3.geo.admin.ch/rest/services/api/SearchServer",
            params=params,
            timeout=10,
        )
        results = resp.json().get("results", [])
        if not results:
            return None
        attrs = results[0].get("attrs", {})

        # ── Street-name validation
        # Build a street phrase from all tokens that:
        #   - don't start with a digit (removes house numbers like "47", "17a")
        #   - are longer than 2 chars (removes single-letter suffixes like "a", "b")
        # Examples:
        #   "Im Dörfli 6"       → "im dörfli"
        #   "Zürichstrasse 47"  → "zürichstrasse"
        #   "Wagerenstrasse 17a"→ "wagerenstrasse"
        street_part = addr.split(",")[0]
        street_words = " ".join(
            w for w in street_part.split()
            if not re.match(r'^\d', w) and len(w) > 2
        ).lower()
        detail = attrs.get("detail", "").lower()
        if street_words and street_words not in detail:
            print(f"swisstopo label mismatch [{addr}] → street_words: '{street_words}' not in detail: '{attrs.get('detail')}'")
            return None

        lat = attrs.get("lat")
        lon = attrs.get("lon")
        if lat is not None and lon is not None:
            return float(lat), float(lon)
    except Exception as e:
        print(f"swisstopo error [{addr}]: {e}")
    return None


def geocode_nominatim(addr: str) -> tuple[float, float] | None:
    """Nominatim fallback. Includes retry on rate-limit.

    Only accepts results with type "house" or "building" — rejects interpolated
    street-midpoint results (type "residential", "road", etc.) which Nominatim
    returns when the exact house number isn't in its database.
    """
    for attempt in range(3):
        try:
            loc = nominatim.geocode(addr, timeout=10, country_codes="ch")
            if loc:
                loc_type = loc.raw.get("type", "")
                if loc_type not in ("house", "building"):
                    print(f"Nominatim rejected [{addr}] – type='{loc_type}' (not house/building)")
                    return None
                return loc.latitude, loc.longitude
            return None
        except GeocoderQuotaExceeded:
            time.sleep(30)
        except Exception as e:
            if "429" in str(e):
                time.sleep(5 * (attempt + 1))
            else:
                print(f"Nominatim error [{addr}]: {e}")
                return None
    return None


def geocode(addr: str | None) -> tuple[float, float] | None:
    """Main geocoding function: swisstopo → Nominatim → None.
    Results are cached. Only returns coordinates inside Uster.
    """
    if not addr:
        return None
    if addr in _geocode_cache:
        return _geocode_cache[addr]

    result = None

    # ── Primary: swisstopo
    coords = geocode_swisstopo(addr)
    if coords and _in_uster(*coords):
        result = coords
        print(result)

    # ── Fallback: Nominatim
    if result is None:
        time.sleep(1.0)  # Nominatim rate-limit
        coords = geocode_nominatim(addr)
        if coords and _in_uster(*coords):
            result = coords
            print(result)

    _geocode_cache[addr] = result
    return result

def _try_geocode(addr: str) -> tuple[float, float] | None:
    """Try swisstopo then Nominatim for a single address string."""
    coords = geocode_swisstopo(addr)
    if coords and _in_uster(*coords):
        return coords
    time.sleep(0.5)
    coords = geocode_nominatim(addr)
    if coords and _in_uster(*coords):
        return coords
    return None


def _strip_letter_suffix(num: str) -> str | None:
    """'17a' → '17',  '26f' → '26',  '14' → None (no suffix to strip)"""
    m = re.match(r'^(\d+)[a-z]+$', num, re.IGNORECASE)
    return m.group(1) if m else None


def _decrement_number(street: str, num: str, max_steps: int = 5) -> tuple[tuple, str] | tuple[None, None]:
    """Try progressively lower house numbers until a geocodable address is found.
    Respects odd/even parity. Returns (coords, tried_address) or (None, None).
    """
    base_m = re.match(r'^(\d+)', num)
    if not base_m:
        return None, None
    base = int(base_m.group(1))
    step = 2 if base > 1 else 1  # keep odd/even parity

    for i in range(1, max_steps + 1):
        candidate = base - i * step
        if candidate < 1:
            break
        candidate_addr = f"{street} {candidate}, Uster, 8610, Switzerland"
        coords = _try_geocode(candidate_addr)
        if coords:
            return coords, candidate_addr
    return None, None


def geocode_with_fallback(addr: str) -> tuple[float | None, float | None, str]:
    """Full geocoding pipeline with fallbacks. Returns (lat, lon, status).

    Status values:
      "swisstopo"           – exact match via swisstopo
      "nominatim"           – exact match via Nominatim
      "needs_review:no_suffix"    – letter suffix stripped (e.g. 17a → 17), match found
      "needs_review:lower_number" – address not found, used a lower house number
      "failed"              – no match found after all fallbacks
    """
    # ── 0. Normalise house number: strip decimal part ("87.2" → "87")
    addr = re.sub(r'(\d+)\.\d+', r'\1', addr)

    # ── 1. Try exact address
    coords = geocode_swisstopo(addr)
    if coords and _in_uster(*coords):
        return coords[0], coords[1], "swisstopo"
    time.sleep(0.5)
    coords = geocode_nominatim(addr)
    if coords and _in_uster(*coords):
        return coords[0], coords[1], "nominatim"

    # Parse street name and number from addr
    street_and_num = addr.split(",")[0].strip()
    m_parts = re.match(r'^(.+?)\s+(\S+)$', street_and_num)
    if not m_parts:
        return None, None, "failed"
    street = m_parts.group(1)
    num    = m_parts.group(2)

    # ── 2. Strip letter suffix and retry (e.g. "17a" → "17", "26f" → "26")
    base_num = _strip_letter_suffix(num)
    if base_num:
        stripped_addr = f"{street} {base_num}, Uster, 8610, Switzerland"
        coords = _try_geocode(stripped_addr)
        if coords:
            print(f"  needs_review: stripped suffix [{addr}] → [{stripped_addr}]")
            return coords[0], coords[1], "needs_review:no_suffix"

    # ── 3. Decrement number (address not yet registered, try lower numbers)
    search_num = base_num if base_num else num
    coords, tried = _decrement_number(street, search_num)
    if coords:
        print(f"  needs_review: lower number [{addr}] → [{tried}]")
        return coords[0], coords[1], "needs_review:lower_number"

    # ── 4. Last resort: geocode street name alone (no house number)
    street_coords = geocode_swisstopo(f"{street}, Uster, 8610, Switzerland")
    if street_coords and _in_uster(*street_coords):
        print(f"  needs_review: street-only fallback [{addr}]")
        return street_coords[0], street_coords[1], "needs_review:street_only"

    # ── 5. Elasticsearch fuzzy search (if enabled)
    if USE_ELASTICSEARCH:
        try:
            from elasticsearch_addon import geocode_elasticsearch
            c = geocode_elasticsearch(addr)
            if c and _in_uster(*c):
                print(f"  elasticsearch fuzzy match [{addr}]")
                return c[0], c[1], "elasticsearch_fuzzy"
        except Exception as e:
            print(f"  Elasticsearch unavailable: {e}")

    return None, None, "failed"


# ── Run geocoding
to_geocode = permits_exploded["parse_status"] != "no_address"
print(f"Geocoding {to_geocode.sum()} addresses  ({(~to_geocode).sum()} skipped: no_address)...")

lats, lons, geocode_statuses = [], [], []

for _, row in tqdm(permits_exploded.iterrows(), total=len(permits_exploded), desc="Geocoding"):
    if row["parse_status"] == "no_address":
        lats.append(None)
        lons.append(None)
        geocode_statuses.append("skipped")
        continue

    lat, lon, status = geocode_with_fallback(row["project_address"])
    lats.append(lat)
    lons.append(lon)
    geocode_statuses.append(status)

permits_exploded["lat"] = lats
permits_exploded["lon"] = lons
permits_exploded["geocode_status"] = geocode_statuses

total = len(permits_exploded)
found = permits_exploded["lat"].notna().sum()
print(f"\nGeocoded: {found}/{total} ({found/total*100:.1f}%)")
print(permits_exploded["geocode_status"].value_counts(dropna=False))

print("\n── needs_review (bitte manuell nachprüfen) ──")
needs_review = permits_exploded[permits_exploded["geocode_status"].str.startswith("needs_review", na=False)]
for _, r in needs_review.iterrows():
    print(f"  [{r['geocode_status']}]  {r['project_address']}  →  ({r['lat']:.5f}, {r['lon']:.5f})")

print("\n── failed (kein Treffer gefunden) ──")
failed = permits_exploded[permits_exploded["geocode_status"] == "failed"]
for _, r in failed.iterrows():
    print(f"  {r['project_address']}")

"""## 6. Spatial join: assign plot polygon

For each geocoded permit point, find the parcel it falls within.
The permit's final geometry **is** the parcel polygon — which is what Part 3 needs
(*"Plots of land that have an active construction permit on them"*).

Permits that could not be geocoded keep `geometry = null`.
"""

# Build GeoDataFrame with point geometry for geocoded permits
geocoded_mask = permits_exploded["lat"].notna()

geocoded_gdf = gpd.GeoDataFrame(
    permits_exploded[geocoded_mask].copy(),
    geometry=gpd.points_from_xy(
        permits_exploded.loc[geocoded_mask, "lon"],
        permits_exploded.loc[geocoded_mask, "lat"],
    ),
    crs="EPSG:4326",
)

# Spatial join: point-in-polygon against plots
plots_slim = plots[["egris_egrid", "nummer", "flaechenmass", "geometry"]].copy()


joined = gpd.sjoin(
    geocoded_gdf,
    plots_slim,
    how="left",
    predicate="within",
)

# Replace point geometry with matched parcel polygon
matched_mask = joined["index_right"].notna()
joined.loc[matched_mask, "geometry"] = (
    plots_slim.loc[joined.loc[matched_mask, "index_right"].astype(int), "geometry"].values
)

print(f"Geocoded permits : {len(geocoded_gdf)}")
print(f"Matched to parcel: {matched_mask.sum()}")
print(f"Point only (no parcel match): {(~matched_mask).sum()}")

# Combine: geocoded (with parcel polygon) + non-geocoded (geometry=None)
not_geocoded = gpd.GeoDataFrame(
    permits_exploded[~geocoded_mask].copy(),
    geometry=[None] * (~geocoded_mask).sum(),
    crs="EPSG:4326",
)

# Align columns
keep_cols = [c for c in joined.columns if c not in ["index_right"]]
permits_final = pd.concat(
    [joined[keep_cols], not_geocoded.reindex(columns=keep_cols)],
    ignore_index=True,
)
permits_final = gpd.GeoDataFrame(permits_final, geometry="geometry", crs="EPSG:4326")

print(f"Final rows        : {len(permits_final)}")
print(f"With geometry     : {permits_final.geometry.notna().sum()}")
print(f"Without geometry  : {permits_final.geometry.isna().sum()}")

"""## 7. Document addresses without geometry"""

no_geom = permits_final[permits_final.geometry.isna()][["id", "title", "project_address", "geocode_status"]]
print(f"{len(no_geom)} permits without geometry:\n")
for _, row in no_geom.iterrows():
    reason = "no address extracted" if not row["project_address"] else "geocoding failed (no match in Uster)"
    print(f"  [{reason}]  {row['title'][:80]}")

"""## 8. Visual check"""

permits_with_geom = permits_final[permits_final.geometry.notna()].copy()

# Assign colour by geocode_status
def _status_color(status: str) -> str:
    if status in ("swisstopo", "nominatim"):
        return "green"
    if isinstance(status, str) and status.startswith("needs_review"):
        return "orange"
    return "gray"

permits_with_geom["_color"] = permits_with_geom["geocode_status"].apply(_status_color)

# Folium map — failed rows have no geometry so they are already excluded
m = plots.explore(color="lightgray", name="Parcels")

for color, group in permits_with_geom.groupby("_color"):
    label = {"green": "Exact match", "orange": "Needs review", "gray": "Other"}.get(color, color)
    group.explore(
        m=m,
        color=color,
        tooltip=["title", "pub_date", "project_address", "geocode_status"],
        name=label,
    )

m.save("permits_map.html")

"""## 9. Export"""

# Convert date to string for GeoJSON serialisation
permits_final["pub_date"] = permits_final["pub_date"].astype(str)

# Drop rows where geometry is truly null (GeoJSON requires valid geometry)
# Keep them in a separate CSV for documentation
permits_no_geom = permits_final[permits_final.geometry.isna()].drop(columns="geometry")
permits_no_geom.to_csv("permits_no_geometry.csv", index=False)
print(f"Saved {len(permits_no_geom)} ungeocodable permits to permits_no_geometry.csv")

permits_geojson = permits_final[permits_final.geometry.notna()].copy()
permits_geojson.to_file("construction_permits.geojson", driver="GeoJSON")
print(f"Saved {len(permits_geojson)} permits to construction_permits.geojson")

"""## 10. Public transport stops (Overpass API)

Fetch all public transport stops within the Uster municipality boundary from
OpenStreetMap via the Overpass API. Covers buses, trams, trains, and S-Bahn.

Saved as `stops.geojson`.
"""

import requests

overpass_url = "https://overpass-api.de/api/interpreter"
overpass_query = """
[out:json][timeout:30]; 
area["name"="Uster"]["boundary"="administrative"]["admin_level"="8"]->.uster;
(
  node["public_transport"="stop_position"](area.uster);
  node["public_transport"="platform"](area.uster);
  node["highway"="bus_stop"](area.uster);
  node["railway"="tram_stop"](area.uster);
  node["railway"="station"](area.uster);
  node["railway"="halt"](area.uster);
);
out body;
"""

print("Fetching public transport stops from Overpass API...")
headers = {"User-Agent": "PopetyUsterPipeline/1.0"}
for url in ["https://lz4.overpass-api.de/api/interpreter",
            "https://overpass.kumi.systems/api/interpreter",
            "https://overpass-api.de/api/interpreter"]:
    r = requests.post(url, data={"data": overpass_query}, headers=headers, timeout=60)
    if r.ok:
        break
r.raise_for_status()
elements = r.json().get("elements", [])
print(f"Raw OSM nodes: {len(elements)}")

stop_rows = []
for el in elements:
    tags = el.get("tags", {})
    stop_rows.append({
        "osm_id":   el["id"],
        "name":     tags.get("name"),
        "type":     (tags.get("public_transport")
                     or tags.get("highway")
                     or tags.get("railway")),
        "network":  tags.get("network"),
        "operator": tags.get("operator"),
        "ref":      tags.get("ref"),           # stop number / line ref
        "geometry": Point(el["lon"], el["lat"]),
    })

stops = gpd.GeoDataFrame(stop_rows, crs="EPSG:4326")

# Drop unnamed nodes (OSM noise: unmapped platforms, duplicates)
stops = stops[stops["name"].notna()].reset_index(drop=True)

# Deduplicate: same name + same location can appear multiple times
# (once as stop_position, once as platform)
stops = stops.drop_duplicates(subset=["name", "geometry"]).reset_index(drop=True)

print(f"Stops after dedup: {len(stops)}")
print(stops["type"].value_counts())

stops.to_file("stops.geojson", driver="GeoJSON")
print(f"\nSaved {len(stops)} stops to stops.geojson")

stops[["name", "type", "network", "operator"]].head(10)

"""## 11. Part 3 – Interactive map

Show on one interactive map:
- **All plots** (light gray background)
- **Plots with an active construction permit** (blue)
- **Plots within a 3-minute walk (≈250 m) of a public transport stop** (green)
- **Public transport stops** (red markers)

Walking speed ≈ 5 km/h → 3 min ≈ 250 m.
Buffer is computed in Swiss LV95 (EPSG:2056) for metric accuracy, then reprojected to WGS84.
"""

import geopandas as gpd
import folium
LayerControl = folium.LayerControl

# ── Load data ─────────────────────────────────────────────────────────────────
plots_map    = gpd.read_file("/Users/nathalieguibert/Downloads/PopetyTest/plots.geojson").to_crs(epsg=4326)
permits_map  = gpd.read_file("/Users/nathalieguibert/Downloads/PopetyTest/construction_permits.geojson").to_crs(epsg=4326)
stops_map    = gpd.read_file("/Users/nathalieguibert/Downloads/PopetyTest/stops.geojson").to_crs(epsg=4326)
print("plots_map columns:", list(plots_map.columns))

# ── Plots with active permits (spatial join) ───────────────────────────────────
# Join permit attributes onto plot geometries so hover shows permit details
joined = gpd.sjoin(permits_map, plots_map, how="inner", predicate="within")

# Aggregate permit info per plot (a plot can have multiple permits)
permit_cols = ["title", "pub_date", "project_address", "geocode_status"]
plot_permits = (
    joined.groupby("index_right")[permit_cols]
    .agg(lambda x: " | ".join(x.dropna().astype(str).unique()))
    .reset_index()
    .rename(columns={"index_right": "plot_idx",
                     "title": "permit_titles",
                     "pub_date": "permit_dates",
                     "project_address": "permit_addresses",
                     "geocode_status": "geocode_statuses"})
)

permit_plot_indices = set(joined["index_right"])
plots_with_permit = plots_map.iloc[sorted(permit_plot_indices)].copy().reset_index()
plots_with_permit = plots_with_permit.rename(columns={"index": "plot_idx"})
plots_with_permit = plots_with_permit.merge(plot_permits, on="plot_idx", how="left")
plots_with_permit = gpd.GeoDataFrame(plots_with_permit, geometry="geometry", crs="EPSG:4326")

# ── Plots within 3-minute walk of a stop (≈250 m buffer) ─────────────────────
# Project to metric CRS, buffer stops, reproject back
stops_lv95  = stops_map.to_crs(epsg=2056)
plots_lv95  = plots_map.to_crs(epsg=2056)
stop_buffer = stops_lv95.copy()
stop_buffer["geometry"] = stops_lv95.buffer(250)          # 250 m = ~3 min walk
stop_buffer_wgs = stop_buffer.to_crs(epsg=4326)

near_stop_ids = set(
    gpd.sjoin(plots_map, stop_buffer_wgs[["geometry"]], how="inner", predicate="intersects")
    .index
)
plots_near_stop = plots_map.loc[sorted(near_stop_ids)].copy()

# ── Build Folium map ──────────────────────────────────────────────────────────
center = [plots_map.geometry.centroid.y.mean(), plots_map.geometry.centroid.x.mean()]
m3 = folium.Map(location=center, zoom_start=14, tiles="CartoDB positron")

# Layer 1: all plots (background)
folium.GeoJson(
    plots_map.__geo_interface__,
    name="All plots",
    style_function=lambda _: {"fillColor": "#d3d3d3", "color": "#aaaaaa",
                               "weight": 0.5, "fillOpacity": 0.4},
    tooltip=folium.GeoJsonTooltip(fields=["egris_egrid", "nummer", "flaechenmass"],
                                   aliases=["EGRID", "Parcel Nr.", "Area (m²)"]),
).add_to(m3)

# Layer 2: plots near transit (green)
folium.GeoJson(
    plots_near_stop.__geo_interface__,
    name="Within 3-min walk of transit",
    style_function=lambda _: {"fillColor": "#2ecc71", "color": "#27ae60",
                               "weight": 1, "fillOpacity": 0.5},
    tooltip=folium.GeoJsonTooltip(fields=["egris_egrid", "nummer"],
                                   aliases=["EGRID", "Parcel Nr."]),
).add_to(m3)

# Layer 3: plots with permits (blue) — hover shows permit details
folium.GeoJson(
    plots_with_permit.__geo_interface__,
    name="Plots with construction permit",
    style_function=lambda _: {"fillColor": "#2980b9", "color": "#1a5276",
                               "weight": 1.5, "fillOpacity": 0.65},
    tooltip=folium.GeoJsonTooltip(
        fields=["egris_egrid", "nummer", "flaechenmass",
                "permit_titles", "permit_dates", "permit_addresses"],
        aliases=["EGRID", "Parcel Nr.", "Area (m²)",
                 "Project(s)", "Date(s)", "Address(es)"],
        sticky=True,
    ),
).add_to(m3)

# Layer 4: transit stops (red markers)
stop_layer = folium.FeatureGroup(name="Public transport stops")
for _, row in stops_map.iterrows():
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=6,
        color="#e74c3c",
        fill=True,
        fill_color="#e74c3c",
        fill_opacity=0.85,
        tooltip=f"{row.get('name', '?')} ({row.get('type', '?')})",
    ).add_to(stop_layer)
stop_layer.add_to(m3)

# Layer 5: 250 m walk buffers (transparent, for reference)
folium.GeoJson(
    stop_buffer_wgs.__geo_interface__,
    name="250 m walk buffer",
    style_function=lambda _: {"fillColor": "#2ecc71", "color": "#27ae60",
                               "weight": 1, "fillOpacity": 0.08, "dashArray": "4"},
    show=False,   # hidden by default, toggle in legend
).add_to(m3)

LayerControl(collapsed=False).add_to(m3)

# ── Legend ────────────────────────────────────────────────────────────────────
legend_html = """
<div style="
    position: fixed;
    bottom: 30px; left: 30px;
    background-color: white;
    border: 2px solid #ccc;
    border-radius: 8px;
    padding: 12px 16px;
    font-family: Arial, sans-serif;
    font-size: 13px;
    z-index: 1000;
    box-shadow: 2px 2px 6px rgba(0,0,0,0.2);
">
    <b style="font-size:14px;">Legend</b><br><br>
    <span style="background:#2980b9;width:14px;height:14px;display:inline-block;border-radius:2px;margin-right:6px;"></span>
    Plot with construction permit<br><br>
    <span style="background:#2ecc71;width:14px;height:14px;display:inline-block;border-radius:2px;margin-right:6px;"></span>
    Within 3-min walk of transit<br><br>
    <span style="background:#e74c3c;width:14px;height:14px;display:inline-block;border-radius:50%;margin-right:6px;"></span>
    Public transport stop<br><br>
    <span style="background:#d3d3d3;width:14px;height:14px;display:inline-block;border-radius:2px;margin-right:6px;border:1px solid #aaa;"></span>
    Other plots
</div>
"""
m3.get_root().html.add_child(folium.Element(legend_html))

out_map = "/Users/nathalieguibert/Downloads/PopetyTest/part3_map.html"
m3.save(out_map)
print(f"Saved Part 3 map to {out_map}")
print(f"  Plots total:              {len(plots_map)}")
print(f"  Plots with permit:        {len(plots_with_permit)}")
print(f"  Plots near transit stop:  {len(plots_near_stop)}")
print(f"  Transit stops shown:      {len(stops_map)}")

"""## Geocoding Strategy – Summary

| | |
|---|---|
| **Primary geocoder** | swisstopo (`api3.geo.admin.ch`) – Swiss federal address register, no rate-limit issues, returns precise building centroids |
| **Fallback** | Nominatim (OpenStreetMap) – global coverage, useful for named buildings; limited to 1 req/s |
| **Validation** | Results outside the Uster municipality boundary (derived from `plots_wgs84.geojson`) are rejected |
| **Multi-address handling** | Titles with multiple streets (split by `/` or `,`) are exploded into one row per address, all sharing the same `id` |
| **Unparseable addresses** | Addresses without a house number (field names, area designations like *"Hinterbreiti Kieswerk"*, *"Chänzeli Sulzbach"*) are skipped – they cannot be resolved to a precise point |
| **Geometry type** | Parcel polygon (from spatial join with `plots_wgs84.geojson`) when available; otherwise the permit row is excluded from the GeoJSON but saved to `permits_no_geometry.csv` |
| **What did not work** | Nominatim alone: ~20% miss rate on Swiss address variants (suffixes like `1c`, `106a`), and the Uster boundary validation is strict – addresses on the edge or with slight geocoding offset were dropped |

"""